version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: izi-web:dev
    container_name: izi-web
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: izi-api:dev
    container_name: izi-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health',r=>{process.exit(r.statusCode===200?0:1)}).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  default:
    name: izi-net


